apiVersion: apps/v1
kind: Deployment
metadata:
  name: uda-cap
  labels:
    app: uda-cap
  namespace: default
spec:
  replicas: 2
  progressDeadlineSeconds: 100
  selector:
    matchLabels:
      app: uda-cap
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: uda-cap
    spec:
      containers:
        - image: docker.io/walidoc/uda-cap
          imagePullPolicy: Always
          name: uda-cap
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: uda-cap
  labels:
    app: uda-cap
spec:
  type: LoadBalancer
  selector:
    app: uda-cap
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP