version: 2.1

executors:
  python:
    docker:
      - image: circleci/python:3.7.3-stretch
  aws:
    docker:
      - image: amazon/aws-cli

jobs:
  lint-app:
    executor: python
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            # Install hadolint
            sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            sudo chmod +x /bin/hadolint
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint    

  build-push-docker-image:
    machine: true
    steps:
      - checkout
      - run:
          name: build and push docker image
          command: |
            # Build image and add a descriptive tag
            docker build --tag=uda-cap .
            # List docker images
            docker image ls
            #Login to docker hub
            docker login --username $DOCKERHUB_USER --password $DOCKERHUB_PWD
            # Push image to a docker repository
            docker tag uda-cap walidoc/uda-cap
            docker push walidoc/uda-cap

  deploy-to-cluster:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          uda-cap
        type: string
    steps:
      - checkout
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          install-kubectl: true
      - kubernetes/create-or-update-resource:
          get-rollout-status: true
          resource-file-path: deployment.yml
          resource-name: deployment/uda-cap

  check-cluster:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          uda-cap
        type: string
    steps:
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
      - run:
          name: check cluster
          command: |
            kubectl get nodes
            kubectl get deployment

orbs:
  aws-eks: circleci/aws-eks@1.0.3
  kubernetes: circleci/kubernetes@0.11.2

  # deploy-to-cluster:
  #   docker:
  #     - image: alpine/k8s:1.15.12
  #   steps:
  #     - checkout
  #     - run:
  #         name: create kubernetes cluster
  #         no_output_timeout: 30m
  #         command: |
  #           # using cli to be able to specify unique name for cluster
  #           eksctl create cluster --name="uda-cap-1" \
  #           --region=eu-central-1 \
  #           --node-type=t2.micro

  #           #deploy docker image to the cluster
  #           kubectl apply -f deployment.yml
  #           echo "Get Deployments =========="
  #           kubectl get deployments
            
  #           echo "Rolling deployment ========"
  #           kubectl set image deployments/uda-cap uda-cap=walidoc/uda-cap:v2
            
  #           echo "Rolling deployment status ============"
  #           kubectl rollout status deployment/uda-cap
            
  #           echo "Get Deployments after rolling updates ==============="
  #           kubectl get deployments

  #     - run:
  #         name: Delete cluster
  #         command: eksctl delete cluster --name uda-cap-1 --region eu-central-1
  #         when: on_fail

workflows:
  deployment:
    jobs:
      - lint-app
      - build-push-docker-image:
          requires: [lint-app]
      # - aws-eks/create-cluster:
      #     cluster-name: uda-cap
      #     aws-region: eu-central-1
      # - deploy-to-cluster:
      #     cluster-name: uda-cap
      #     requires: [aws-eks/create-cluster]
      # - aws-eks/update-container-image:
      #     cluster-name: uda-cap
      #     container-image-updates: uda-cap=walidoc/uda-cap
      #     post-steps:
      #         - kubernetes/delete-resource:
      #             resource-names: uda-cap
      #             resource-types: deployment
      #             wait: true
      #     record: true
      #     requires: [deploy-to-cluster]
      #     resource-name: deployment/uda-cap
      # - check-cluster:
      #     cluster-name: uda-cap
      #     requires: [aws-eks/update-container-image]
      # - aws-eks/delete-cluster:
      #     cluster-name: uda-cap
      #     requires: [check-cluster]