version: 2.1
jobs:
  lint-app:
    docker:
    # Use the same Docker base as the project
      - image: python:3.7.3-stretch
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
                chmod +x /bin/hadolint
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      # run lint!
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint    

  build-push-docker-image:
    docker:
      - image: docker:17.05.0-ce-git
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PWD 
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build and push docker image
          command: |
            # Build image and add a descriptive tag
            docker build --tag=uda-cap .
            # List docker images
            docker image ls
            #Login to docker hub
            docker login --username $DOCKERHUB_USER --password $DOCKERHUB_PWD
            # Push image to a docker repository
            docker tag uda-cap walidoc/uda-cap
            docker push walidoc/uda-cap
            
  deploy-to-cluster:
    docker:
      - image: alpine/k8s:1.15.12
    working_directory: ~/repo
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["dd:c3:62:b3:4e:04:de:b0:3c:60:59:89:33:38:76:c1:e7:16:48:18"]
      - run:
          name: create kubernetes cluster
          command: |
            # using cli to be able to specify unique name for cluster
            eksctl create cluster --name="uda-cap-${CIRCLE_WORKFLOW_ID:0:7}" \
            --region=us-east-1 --zones=us-east-1a,us-east-1b \
            --node-type=t3.medium --ssh-access --ssh-public-key	uda-cap-key --managed

            #view your cluster nodes
            echo "Getting cluster nodes..."
            kubectl get nodes -o wide
            
            #Get pods on cluster
            echo "Getting pods..."
            kubectl get pods --all-namespaces -o wide
            
            #list services
            echo "Getting services..."
            kubectl get services --sort-by=.metadata.name
            
            echo "Getting pods again..."
            kubectl get pods --all-namespaces -o wide
            
            echo "Get Deployments ..."
            kubectl get deployments
            
            echo "Rolling deployment------"
            kubectl set image deployment/uda-cap uda-cap=walidoc/uda-cap:v2
            
            echo "Rolling deployment status-----"
            kubectl rollout status deployment/uda-cap
            
            echo "Get Deployments after rolling updates-----"
            kubectl get deployments
            
            echo "Check Rolling deployment status again------"
            kubectl rollout status deployment/uda-cap
      # - run:
      #     name: deploy docker image to the cluster
      #     command: |
      #       #deploy docker image to the cluster
      #       kubectl apply -f deployment.yml
      #       echo "Get Deployments ..."
      #       kubectl get deployments

workflows:
  default:
    jobs:
      - lint-app
      - build-push-docker-image:
          requires: [lint-app]
      - deploy-to-cluster:
          requires: [build-push-docker-image]